version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'apolo96/php-7.4-nginx'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'main'
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1